### ISSUE TITLE
UI Design for Quick T-Shirt Checkoff

### ISSUE THREAD

**Issue by saabdoli** [edbirmingham/network#166]
![screenshot from 2016-01-20 12 38 09](https://cloud.githubusercontent.com/assets/10284864/12459209/256a7b58-bf73-11e5-8b42-884352912598.png)
We want to make the T-Shirt Receipt Checkoff more user-friendly.

**Comment by rthbound** [comment]
:+1: :tshirt:

**Comment by c-collins** [comment]
![t-shirt-swiping](https://cloud.githubusercontent.com/assets/1730632/12485954/1c39701c-c026-11e5-8e7a-47f9f492c05e.jpg)

**Comment by rthbound** [comment]
@c-collins I like the idea :sparkles: :bulb:, but I have a few concerns:

I worry that the usage isn't intuitive enough because it's not clear (especially on a tough device) that the control can be interacted with.

Also, if I slide left to say "has T-shirt", what do I do to say "my mistake, member does _not_ have a T-shirt"? Slide right?

I do have a suggestion though, see the "Label Text" example here: http://www.bootstrap-switch.org/examples.html

The bootstrap-switch feature should behave much like your design, but provide a little more clarity to the end user.
