### ISSUE TITLE
Editing a user makes them unusable.

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#224]
When a user is edited, something is getting messed up that makes it no longer possible to log in as that user.

**Comment by andreburto** [comment]
This issue seems to come down to one of three issues:

1. There are two functions named $scope.updateUserProfile, one is in /public/dist/application.js ast line 1582, and the other is in /public/modules/users/controllers/settings.client.controller.js at line 42.

2. The password in $scope.user is being erased.

3. The password salt is messing up, which is unlikely since it initially works.

I have not created a branch for this yet as I'm still looking for the cause.

**Comment by andreburto** [comment]
Looks like the salted+hashed password is being sent when a profile is requested to edit the profile. If that is being sent back along with the profile update this could be responsible for changing the password. Looking into limiting what's called and PUT to the server.
