### ISSUE TITLE
Add an end time to events

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#253]
Events already have a start time and need to also have an end time.  They will not span multiple days so they don't need an end date.  Add this information to the event list and the event show.

**Comment by jzw** [comment]
@anthonycrumley a couple of things:

1. I don't see a starts_at or start_time on network_events. I assume you are referring to secheduled_at.
2. Instead of adding a end_time (datetime) column, I was wondering if it would be okay to add a duration column that would be an integer, and represents the number of minutes the event would last.  Therefore end_time would be `scheduled_at + duration.minutes`.

**Comment by anthonycrumley** [comment]
@jzw That seems reasonable.
