### ISSUE TITLE
Add participation level

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#285]
When a member participates in an event, we need to record whether they are a volunteer or attendee.

**Comment by tsmith1024** [comment]
Since I'm still new to the project, I wanted to discuss before (if I've got time before somebody else does) taking this one on. 

I'm thinking about a participation intermediate model with a level attribute between members and events. Rough details can be found below. Does that fit with the plan? 

Let me know if there's something else planned, as that'll help me understand both this bit of the project and the whole thing better. I noticed the volunteer assignment already associated with the event model, so I wasn't sure whether my idea would fit with that or if a similar attendee assignment would be the right fit here. 

Whatever the end result is, getting this out of the way will set up things nicely for #279, #233, and #269. Thanks!

---
Member:
has_many participations
has_many events through participations

Event:
has_many participations
has_many participants (members) through participations

Participation:
belongs_to member (member_id)
participation has_one event (event_id)
level attribute (value of 'volunteer' or 'attendee', allowing for expansion if new types of participation are needed later)

**Comment by anthonycrumley** [comment]
@tsmith1024 Taylor, you are absolutely correct.  👍 

Sorry for the delayed response.

**Comment by anthonycrumley** [comment]
@tsmith1024 I wanted to make sure you are aware of the hackathon Wednesday at the Innovation Depot.  We would love to have you join us.  Here is the blurb Ed Birmingham sent out to advertise the event.

Come one, come all! Join the Birmingham Education Foundation and the Education Advisory Board for a Hackathon on August 24 at Innovation Depot! Committed to ensuring more Birmingham City students are on the pathway to college and career readiness, the Ed Foundation is partnering with EAB to develop an open source Network Application to match students and residents with community resources and partners. Since this application is open source, we are inviting programmers of all experience levels and backgrounds to participate in this hackathon. Expert support will be present on site, as well as roles for everyone from front-end developers to back-end developers. The goal of this hackathon is to prepare our application for roll out by September 1. We will get started in Innovation Depot’s UAB iLab at 11:30am and go until 5:00pm, but feel free to stop by at any point. Lunch will be provided on a first-come, first-served basis. To learn more about this project, check out the framework at https://github.com/edbirmingham/network.

**Comment by tsmith1024** [comment]
In Progress on this one.

Also, thanks for the invite @anthonycrumley! I may be able to make it, at least for a bit, depending on work needs at the office.

**Comment by tsmith1024** [comment]
Unless there's anything else this one needs, is this completed by PR #344?

**Comment by anthonycrumley** [comment]
@tsmith1024 I believe that does complete it.  Thanks!!
