### ISSUE TITLE
Setup continuous integration.

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#4]
Setup a service like Jenkins that will run the test suite every time a commit is made to the repository.

**Comment by tmiller** [comment]
Can you explain what you mean by continuous integration?

**Comment by tmiller** [comment]
Automated testing is probably a better name for this, I recommend using Travis CI since it is free for open source projects and works very similar to CircleCI. Very easy to configure.

**Comment by anthonycrumley** [comment]
Isn't Continuous Integration what CI stands for?  Why would it not be called Continuous Integration?  Is it because we would not be committing everyday?

We would be pretty much doing what this link says... http://www.thoughtworks.com/continuous-integration

**Comment by anthonycrumley** [comment]
:+1:  On Travis CI.

**Comment by tmiller** [comment]
I was thinking it was because we aren't automatically merging feature branches into a shared mainline branch which seems to be the definition from Wikipedia.

> Continuous integration (CI) is the practice, in software engineering, of merging all developer working copies with a shared mainline several times a day. It was first named and proposed by Grady Booch in his 1991 method,

However, this was written during a different time. By that definition merging mainline into your feature branches or rebasing your feature branch on top of mainline regularly seems to meet the very definition of CI.

**Comment by tmiller** [comment]
Work is being done here #112
