### ISSUE TITLE
exporting list of participants from Network Night

### ISSUE THREAD

**Issue by marshallpollard** [edbirmingham/network#92]
Typically, we share the sign in information with our Connectors so they can effectively follow up. 

Is it possible to export the list of all the individuals who signed in at a Network Night in a way that allows us to share with Connectors?

**Comment by anthonycrumley** [comment]
@marshallpollard Here is a brainstormed list of ideas:
* Give connectors access to the Network Database.  #56 will need to be completed so they can see the list.
* Email the list to someone.
* Print the list.
* Export the list to a csv.

I recommend giving them access to the Network Database, then we can add functionality in the future that would help them do their job.  As part of this we would all need to tighten up the permissions so that they can add users or delete things.

**Comment by andreburto** [comment]
Would this be under the "Participants" menu?
